version: '3.8'

services:
  backup-system:
    build: .
    container_name: backup-system
    restart: unless-stopped
    # Monta o arquivo de configuração local no contêiner
    # Garante que as configurações sejam persistentes e fáceis de gerenciar.
    volumes:
      - ./config_avancada.json:/app/config_avancada.json
      # Opcional: monte o diretório de credenciais se necessário
      # - ./credentials:/app/credentials
      # Diretório de origem (somente leitura para segurança)
      - /path/to/your/source/data:/data/source:ro
      # Diretório de destino para backups locais
      - /path/to/your/local/backups:/data/backups
    environment:
      # Define o fuso horário para logs e agendamentos corretos
      - TZ=America/Sao_Paulo
    healthcheck:
      # Comando para verificar a saúde do contêiner
      test: ["CMD", "python", "health_check.py"]
      interval: 5m # Verifica a cada 5 minutos
      timeout: 30s # Tempo limite para a verificação
      retries: 3 # Tenta 3 vezes antes de marcar como não saudável
